### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Crims-on** [DiscordSaver/nexe-decompiler#1]
Can't decompile
```
TypeError: key.trim(...).replaceAll is not a function
    at main (exe-decompiler\decompile.js:42:35)
    at Object.handler (nexe-decompiler\decompile.js:78:13)
    at nexe-decompiler\node_modules\yargs\build\index.cjs:1:9052
    at j (nexe-decompiler\node_modules\yargs\build\index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (nexe-decompiler\node_modules\yargs\build\index.cjs:1:9021)
    at M.runCommand (nexe-decompiler\node_modules\yargs\build\index.cjs:1:7206)
    at Jt.[runYargsParserAndExecuteCommands] (\nexe-decompiler\node_modules\yargs\build\index.cjs:1:56370)
    at Jt.parse (nexe-decompiler\node_modules\yargs\build\index.cjs:1:38250)
    at Jt.get [as argv] (nexe-decompiler\node_modules\yargs\build\index.cjs:1:59486)
    at Object.<anonymous> (nexe-decompiler\decompile.js:79:11)
```

**Comment by DiscordSaver** [comment]
Can you send over the compiled nexe file?

**Comment by Crims-on** [comment]
> Can you send over the compiled nexe file?

https://anonfiles.com/n3k4H3Ebx6/darks_exe

**Comment by DiscordSaver** [comment]
Seems like the file is not compiled with nexe. I am looking to see how it was compiled now.

**Comment by DiscordSaver** [comment]
Just realized anonfiles sent me the wrong file. I ran nexe-decompile on the original darks.exe and it decompiled fine.

**Comment by DiscordSaver** [comment]
It seems like the issue comes from an old version of Nodejs. Please upgrade upgrade to nodejs version 15 or newer.

**Comment by Crims-on** [comment]
Oh Thank you
